anime = peripheral.wrap("top")
function Hii()
    function LeftArm(z,t)
        sleep(t)
        anime.setFace("happy")
        anime.setHeadRot(0,0,10)
        anime.setBodyRot(0,0,10)
        anime.setLeftArmRot(0,0,z)
        anime.push()
    end
    LeftArm(-170,0)
    LeftArm(-150,0.5)
    LeftArm(-180,0.5)
    sleep(0.5)
    anime.setFace("normal")
    anime.push()
end
function Duvida()
    anime.setFace("question")
    anime.setHeadRot(30,0,0)
    anime.setLeftArmRot(-90,45,10)
    anime.push()
    sleep(1)
    anime.setFace("normal")
    anime.push()
end
function Desligar()
    anime.setBodyRot(45,0,0)
    anime.setLeftArmRot(-45,0,0)
    anime.setRightArmRot(-45,0,0)
    anime.setHeadRot(45,0,0)
    anime.push()
end
